# Generated by Django 6.0 on 2026-02-09 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_articles', to='articles.tag')),
            ],
            options={
                'db_table': 'article_tags',
                'constraints': [models.UniqueConstraint(fields=('article', 'tag'), name='unique_article_tag')],
            },
        ),
    ]
